reservation/urls.py
from django.urls import path
from . import views 

app_name = 'reservation'

urlpatterns = [
    path('vehicle_reservation/<int:vehicle_id>/', views.vehicle_booking, name='vehicle_booking'),
    path('booking_status/<int:reservation_id>/', views.booking_status, name='booking_status'),
    path('reject_booking/<int:reservation_id>/', views.reject_booking, name='reject_booking'),
    path('payment/<int:reservation_id>/', views.payment, name='payment'),
    path('user_booking/', views.user_booking, name='user_booking'),
    path ('driver_booking/', views.driver_booking, name='driver_booking'),
    path('driver_booking/<int:reservation_id>/', views.driver_booking, name='driver_booking'),
]

sawari/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_acc.urls')),  # Include URLs from user_acc app
    path('vehicle/', include(('vehicles.urls', 'vehicles'), namespace='vehicles')),
    path('reservation/', include('reservation.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/models.py
from datetime import timedelta
from django.utils import timezone
from django.db import models
from django.conf import settings
from vehicles.models import Vehicle

class Reservation(models.Model):
    STATUS_CHOICES = [
        ('available', 'available'),
        ('pending', 'pending'),
        ('approved', 'approved'),
        ('completed', 'completed'),
        
    ]

    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, related_name='reservations')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reservations')
    start_date = models.DateField()
    end_date = models.DateField()
    purpose = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='available')
    created_at = models.DateTimeField(auto_now_add=True)
    payment_proof = models.ImageField(upload_to='payment_proofs/', null=True, blank=True)
    payment_status = models.CharField(max_length=20 , default='Unpaid')
    
    def can_user_cancel(self):
        """User can cancel if more than 2 days remain."""
        return timezone.now().date() <= self.start_date - timedelta(days=2)

    def can_owner_cancel(self):
        """Owner can cancel if more than 5 days remain."""
        return timezone.now().date() <= self.start_date - timedelta(days=5)

reservation/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['start_date', 'end_date', 'purpose']
        widgets = {
            'start_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'w-1/4 px-4 py-2 rounded-lg bg-gray-700 text-white border border-gray-600'
            }),
            'end_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'w-1/4 px-4 py-2 rounded-lg bg-gray-700 text-white border border-gray-600'
            }),
            'purpose': forms.Textarea(attrs={
                'class': 'w-1/2 h-32 px-4 py-2 rounded-lg bg-gray-700 text-white border border-gray-600',
                'placeholder': 'Enter purpose of reservation...'
            }),
        }

reservation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from vehicles.models import Vehicle
from user_acc.models import User_profile
from .forms import ReservationForm
from .models import Reservation
from django.core.mail import send_mail, EmailMessage
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings

@login_required
def vehicle_booking(request, vehicle_id):
    vehicle = get_object_or_404(Vehicle, id=vehicle_id)

    # Check if the user already has a pending or approved reservation for this vehicle
    existing_reservation = Reservation.objects.filter(
        user=request.user,
        vehicle=vehicle,
        status__in=['pending', 'approved']
    ).first()

    if existing_reservation:
        messages.error(request, "You already have a reservation for this vehicle.")
        return redirect('viewer_homepage')

    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user
            reservation.vehicle = vehicle
            reservation.status = 'pending'
            reservation.save()
            send_mail(
                subject='Reservation Request',
                message=(
                    f'New reservation request for {vehicle.vehicle_type} '
                    f'from {reservation.start_date} to {reservation.end_date}.'
                ),
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[vehicle.owner.email],
            )
            messages.success(request, "Reservation requested successfully!")
            return redirect('viewer_homepage')
    else:
        form = ReservationForm()

    return render(request, 'reservation/vehicle_booking.html', {
        'vehicle': vehicle,
        'form': form,
    })


@login_required
def booking_status(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    vehicle = reservation.vehicle

    # Ensure only the driver who owns the vehicle can access
    if vehicle.owner != request.user:
        messages.error(request, "You are not allowed to manage this reservation.")
        return redirect('vehicles:driver_homepage')

    if request.method == "POST":
        action = request.POST.get("action")
        if action in ["approved", "completed", "available", "pending"]:
            reservation.status = action
            reservation.save()


           
            if action == "approved":
                subject = 'Reservation Approved'
                body = (
                    f'Your reservation of {vehicle.vehicle_type} '
                    f'from {reservation.start_date} to {reservation.end_date} has been approved.\n\n'
                    f'Please pay the amount to complete the booking.'
                    f'{reservation.vehicle.cost_per_day } per day'
                    f' And upload the payment proof in the payment section.'
                )

                email = EmailMessage(
                    subject=subject,
                    body=body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    to=[reservation.user.email],
                )

                # Attach QR code if it exists
                if vehicle.qr_image and vehicle.qr_image.path:
                    email.attach_file(vehicle.qr_image.path)

                email.send()
        
            messages.success(request, f"Reservation status updated to {action}.")
            return redirect('vehicles:driver_homepage')  # redirect back to driver homepage
        
        

    return render(request, "reservation/booking_status.html", {
        "reservation": reservation,
        "vehicle": vehicle
    })

@login_required
def reject_booking(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    user = reservation.user
    if request.method == "POST":
        reservation.delete()
        send_mail(
            subject='Reservation Rejected',
            message=(
                f'Your reservation of {reservation.vehicle.vehicle_type} '
                f'from {reservation.start_date} to {reservation.end_date} has been rejected.'
            ),
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[reservation.user.email],
        )
        send_mail(
            subject='Reservation Rejected',
            message=(
                f'Your reservation of {reservation.vehicle.vehicle_type} '
                f'from {reservation.start_date} to {reservation.end_date} has been rejected.'
            ),
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[reservation.vehicle.owner.email],
        )
        messages.success(request, "Reservation has been rejected.")
        return redirect('reservation:user_booking')
    return render(request, 'reservation/reject_booking.html', 
                  {'reservation': reservation,
                     'user': user})
                                                            

@login_required
def payment(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    vehicle = reservation.vehicle
    if reservation.user != request.user:
        messages.error(request, "You are not authorized to view this payment page.")
        return redirect('viewer_homepage')
    if request.method == 'POST':
        payment_proof = request.FILES.get('payment_proof')
        if payment_proof:

            reservation.payment_status = 'Paid'
            reservation.payment_proof = payment_proof
            reservation.save()
            
            messages.success(request, "Payment proof uploaded successfully..")
            subject = 'Payment completed'
            body = (
                    f'Payment is done for your reservation of {reservation.vehicle.vehicle_type} '
                    f'from {reservation.start_date} to {reservation.end_date} has been submitted.'
                    f'Please verify the payment proof to complete the booking. ANd update the status to completed.'
                )

            email = EmailMessage(
                    subject=subject,
                    body=body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    to=[reservation.vehicle.owner.email],
                )

                # Attach QR code if it exists
            if reservation.payment_proof and reservation.payment_proof.path:
                    email.attach_file(reservation.payment_proof.path)

            email.send()
        
            return redirect('viewer_homepage')
        else:
            reservation.payment_status ='Unpaid'
            messages.error(request, "Please upload a valid payment proof.")
    return render(request, 'reservation/payment.html', {'reservation': reservation, 'vehicle': vehicle})


def user_booking(request):
    reservations = Reservation.objects.filter(user=request.user)
    return render(request, 'reservation/user_booking.html', {'reservations': reservations})



@login_required
def driver_booking(request, reservation_id=None):
    # Get all reservations for vehicles owned by the logged-in user
    reservations = Reservation.objects.filter(vehicle__owner=request.user)

    # Handle POST actions
    if request.method == 'POST' and reservation_id:
        # Get the specific reservation being updated
        reservation = get_object_or_404(Reservation, id=reservation_id)
        vehicle = reservation.vehicle  # always refer to the vehicle of this reservation
        action = request.POST.get('action')

        if action in ['available', 'pending', 'approved', 'completed']:
            reservation.status = action
            reservation.save()

            if action == "approved":
                total_cost = vehicle.cost_per_day * (reservation.end_date - reservation.start_date).days
                subject = 'Reservation Approved'
                body = (
                    f'Your reservation of {vehicle.vehicle_type} '
                    f'from {reservation.start_date} to {reservation.end_date} has been approved.\n\n'
                    f'Please pay the amount of Rs. {total_cost} to complete the booking.'
                )
                email = EmailMessage(
                    subject=subject,
                    body=body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    to=[reservation.user.email],
                )
                if vehicle.qr_image and vehicle.qr_image.path:
                    email.attach_file(vehicle.qr_image.path)
                email.send()

            elif action == "completed":
                subject = 'Reservation Completed'
                body = (
                    f'Your reservation of {vehicle.vehicle_type} '
                    f'from {reservation.start_date} to {reservation.end_date} has been marked as completed.\n\n'
                    f'Thank you for using our service!'
                )
                send_mail(
                    subject=subject,
                    message=body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[reservation.user.email],
                )

            messages.success(request, f"Reservation marked as {action} successfully.")
        return redirect('reservation:driver_booking')

    # Render template with all reservations
    return render(request, 'reservation/driver_booking.html', {
        'reservations': reservations,
    })

reservation/templates/reservation/booking_status.html
{% extends 'base.html' %}

{% block content %}
<div class="p-6 bg-gray-800 text-white rounded-lg shadow-lg">
    <h2 class="text-2xl font-bold mb-4">Reservation Details</h2>

    <p><strong>User:</strong> {{ vehicle.name }}</p>
    <p><strong>Email:</strong> {{ reservation.user.email }}</p>
    <p><strong>Vehicle:</strong> {{ vehicle.vehicle_type}}</p>
    <p><strong>Start Date:</strong> {{ reservation.start_date }}</p>
    <p><strong>End Date:</strong> {{ reservation.end_date }}</p>
    <p><strong>Purpose:</strong> {{ reservation.purpose }}</p>
    <p><strong>Status:</strong> {{ reservation.status|title }}</p>

    <form method="post" class="mt-4">
        {% csrf_token %}
        <label class="block mb-2"><strong>Update Status:</strong></label>
        <select name="action" class="bg-gray-700 text-white p-2 rounded-lg mb-4">
            <option value="pending" {% if reservation.status == 'pending' %}selected{% endif %}>Pending</option>
            <option value="approved" {% if reservation.status == 'approved' %}selected{% endif %}>Approved</option>
        </select>
        
        <button type="submit" class="bg-blue-600 py-2 px-4 rounded-lg">Update Status</button>
    </form>
</div>
{% endblock %}

reservation/templates/reservation/driver_booking.html
{% extends 'base.html' %}
{% block content %}
<h2 class="text-2xl font-bold mb-4 text-white m-4">Your Bookings</h2>
<table class="table-auto w-full border-collapse border border-gray-300 m-4 p-4 ">
    <tr class="m-4 p-4 bg-gray-800 text-white text-center border-t border-gray-300">
        <th>Reservation ID</th>
        <th>Vehicle Type</th>
        <th>Customer</th>
        <th>Pickup Date</th>
        <th>Return Date</th>
        <th>Status</th>
        <th>Payment</th>
        <th>Actions</th>
    </tr>
    {% for reservation in reservations %}
        <tr class="text-white text-center border-t border-gray-300">
            <td>{{ reservation.id }}</td>
            <td>{{ reservation.vehicle.vehicle_type }}</td>
            <td>{{ reservation.user }}</td>
            <td>{{ reservation.start_date }}</td>
            <td>{{ reservation.end_date }}</td>
            <td>
                <form method="post" action="{% url 'reservation:driver_booking' reservation.id %}">
                    {% csrf_token %}
                    <select name="action" class="bg-gray-700 text-white p-2 rounded-lg mb-2">
                        <option value="available" {% if reservation.status == 'available' %}selected{% endif %}>Available</option>
                        <option value="pending" {% if reservation.status == 'pending' %}selected{% endif %}>Pending</option>
                        <option value="approved" {% if reservation.status == 'approved' %}selected{% endif %}>Approved</option>
                        <option value="completed" {% if reservation.status == 'completed' %}selected{% endif %}>completed</option>
                    </select>
                    <button type="submit" class="btn btn-dash btn-success">Save</button>
                </form>
            </td>
            <td>{{ reservation.payment_status }}</td>
            <td>
                <a href="{% url 'reservation:reject_booking' reservation.id %}" class="btn btn-dash btn-error m-2">Reject</a>
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

reservation/templates/reservation/payment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-center items-center min-h-screen bg-base-200">
    <div class="w-full max-w-md p-6 bg-base-100 rounded-lg shadow-md">
        <h2 class="text-2xl font-bold text-center mb-6">Payment</h2>
        
        <!-- QR Code Section -->
        <div class="flex justify-center mb-6">
            <p class=""></p>
            {% if reservation.vehicle.qr_image %}
                <div class="flex justify-center mb-6">
                    <img src="{{ reservation.vehicle.qr_image.url }}" alt="QR Code Pay" class="w-48 h-48 object-contain">
                </div>
            {% else %}
                <p class="text-center text-gray-500">QR code not available.</p>
            {% endif %}

        </div>
        <span style =" color: rgb(255, 0, 0);">You need to submit the screenshot of your payment as proof</span><br>
        <span>Amount per day: $ {{ reservation.vehicle.cost_per_day }}</span>
        <form method="POST" enctype="multipart/form-data" class="mt-4">
            {% csrf_token %}
            <label class="block mb-1">Upload Payment Proof</label>
            <input type="file" name="payment_proof" accept="image/*" required
                class="w-full border rounded-lg p-2 mb-4">
            <button type="submit" class="bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700">
                Submit
            </button>
            <a href="{% url 'reservation:user_booking' %}" class="btn btn-error bg-red-600 text-white py-2 px-4 rounded-lg hover:bg-red-700 ml-2">Cancel</a>
        </form>


    </div>
</div>
{% endblock %}

reservation/templates/reservation/reject_booking.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="card card-border bg-base-100 w-96 ">
        <div class="card-body flex justify-center">
            <h2 class="card-title" style="color: red; font-weight: bold; font-size: 24px">Reject Booking</h2>

            <form action="{% url 'reservation:reject_booking' reservation.id %}" method="post" >
                {% csrf_token %}
                <p class="text-white">Are you sure you want to cancel this booking?</p><br>

                <img src="{{ reservation.vehicle.vehicle_image.url }}" alt="" class=" rounded "><br>
                <span class="text-white">Owner: {{ reservation.vehicle.name }}</span><br>
                <span class="text-white">Vehicle Type: {{ reservation.vehicle.vehicle_type }}</span><br>
                <span class="text-white">Date: {{ reservation.start_date }} to {{ reservation.end_date }}</span><br>
                <span class="text-white">Status: <span style="color: rgb(229, 232, 230); font-weight: bold;">{{ reservation.status }}</span></span>
                <div class="card-actions justify-end">
                    <button type="submit"
                            class="btn bg-red-600 hover:bg-red-700 p-1 mt-4 text-white rounded font-semibold">
                        Yes
                    </button>



                    <a href="{% url 'reservation:user_booking' %}" class="btn bg-green-600 hover:bg-green-700 p-1 mt-4 text-white rounded font-semibold">
                        No
                    </a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

reservation/templates/reservation/user_booking.html
{% extends 'base.html' %}
{% block content %}
<h2 class="text-2xl font-bold mb-4 text-white m-4">Your Bookings</h2>
    <table class="table-auto w-full border-collapse border border-gray-300 m-4 p-4 ">
        {% csrf_token %}
        <tr class="m-4 p-4 bg-gray-800 text-white text-center border-t border-gray-300">
            <th>Reservation ID</th>
            <th>Vehicle Type</th>
            <th>Owner</th>
            <th>Pickup Date</th>
            <th>Return Date</th>
            <th>Status</th>
            <th>Payment</th>
        </tr>
        {% for reservation in reservations %}
            <tr class="text-white text-center border-t border-gray-300">
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.vehicle.vehicle_type }}</td>
                <td>{{ reservation.vehicle.name }}</td>
                <td>{{ reservation.start_date }}</td>
                <td>{{ reservation.end_date }}</td>
                <td>{{ reservation.status }}</td>
                <td>{{reservation.payment_status}}</td>
                <td>
                    <a href="{% url 'reservation:reject_booking' reservation.id %} " class="btn btn-dash btn-error m-2">Reject</a> |
                    <a href="{% url 'reservation:payment' reservation.id %}" class="btn btn-dash btn-success m-2">Payment</a>

                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

reservation/templates/reservation/vehicle_booking.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2 class="text-5xl font-bold mb-4 w-full decoration-[#4169e1]">
        Book {{ vehicle.vehicle_type }}
    </h2>


  <form method="post" class="space-y-4 ">
    {% csrf_token %}
    
    {% for field in form %}
        <div class="mb-4 text-white flex flex-col m-4">
            <label for="{{ field.id_for_label }}" class="block text-sm font-medium mb-1">{{ field.label }}</label>
            <div >{{ field }}</div>
            {% if field.help_text %}
                <p class="text-xs text-gray-400">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
                <p class="text-red-500 text-xs mt-1">{{ error }}</p>
            {% endfor %}
        </div>
    {% endfor %}
    
    <button type="submit" class="btn btn-primary bg-blue-500 text-white px-4 py-2 rounded">
      Submit Reservation
    </button>
  </form>
{% endblock %}