sawari/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_acc.urls')),  # Include URLs from user_acc app
    path('vehicle/', include(('vehicles.urls', 'vehicles'), namespace='vehicles')),
    path('reservation/', include('reservation.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vehicles/urls.py
from django.urls import path
from . import views

app_name = 'vehicles'
urlpatterns = [
    path('register_vehicle/', views.register_vehicle, name='register_vehicle'),
    path('driver_homepage/', views.driver_homepage, name='driver_homepage'),
    
]

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SAWARI</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
</head>

<body class="bg-gary-500 font-serif leading-normal tracking-normal text-white">
    
   {% block navbar %}
        <div class="navbar bg-base-100 shadow-sm h-14">
            <!-- Hamburger button (optional)
            <div class="flex-none">
                <button class="btn btn-square btn-ghost">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block h-5 w-5 stroke-current">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                </button>
            </div> -->

            <!-- Brand / Logo -->
            {% if request.user.user_type == 'customer'%}
                <div class="flex-1">
                    <a href="{% url 'viewer_homepage' %}" class="btn from-blue-500 to-purple-600 text-white font-bold text-xl rounded-xl shadow-md hover:scale-105 transform transition">
                        <img src="{% static 'img/sawari_white.png' %}" alt="Sawari Logo" class="h-20 w-auto">
                    </a>
                </div>
            {% else %}
                <div class="flex-1">
                    <a href="{% url 'vehicles:driver_homepage' %}" class="btn from-blue-500 to-purple-600 text-white font-bold text-xl rounded-xl shadow-md hover:scale-105 transform transition">
                        <img src="{% static 'img/sawari_white.png' %}" alt="Sawari Logo" class="h-20 w-auto">
                    </a>
                </div>
            {% endif %}

            <!-- Three-dot dropdown -->
            <div class="flex-none">
                <div class="dropdown dropdown-end">
                    <button tabindex="0" class="btn btn-square btn-ghost">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block h-5 w-5 stroke-current">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
                        </svg>
                    </button>
                    <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
                        {% if request.user.user_type == 'driver' or request.user.user_type == 'admin' %}
                            <li><a href="{% url 'vehicles:register_vehicle' %}">List Vehicle</a></li>{% endif %}
                        <li><a href="{% url 'login_view' %}">Login</a></li>
                        <li><a href="{% url 'first_view' %}">Logout</a></li>
                        
                        
                        <!-- Add more menu items if needed -->
                    </ul>
                </div>
            </div>
        </div>
    {% endblock navbar %}

    {% block about_us %}
        
    {% endblock about_us %}

    {% block content %}

    {% endblock content %}

    

</body>
</html>